language: php

matrix:
  fast_finish: true
  include:
    - env: DB=mysql; MW=REL1_27; PHPUNIT=4.8.*
      php: 5.6
    - env: DB=sqlite; MW=1.25.6
      php: 5.5
    - env: DB=sqlite; MW=1.28.2
      php: 7.0

install:
  - bash ./build/travis/install-mediawiki.sh
  - bash ./build/travis/install-semantic-result-formats.sh

script:
  - bash ./build/travis/run-tests.sh

notifications:
  irc:
    channels:
      - "chat.freenode.net#semantic-mediawiki"
    on_success: never
    on_failure: always

cache:
  directories:
    - $HOME/.composer/cache
