language: php

os:
  - linux

env:
  global:
    # fix "Xdebug 3 is installed by default, breaking builds"
    # see https://travis-ci.community/t/xdebug-3-is-installed-by-default-breaking-builds/10748
    - XDEBUG_MODE=coverage

services:
  - mysql
  - postgresql

jobs:
  fast_finish: true
  include:
    # 1) sqlite, previous MW LTS stable, current SMW stable
    - env: DB=sqlite; MW=REL1_31; SMW=3.2.2; MERMAID=2.1.0
      php: 7.1
    # 2) postgres, current MW non-LTS stable, current SMW stable
    - env: DB=postgres; MW=REL1_34; SMW=3.2.2
      php: 7.2
    # 3) mysql, current MW LTS stable, current SMW stable, COVERAGE
    # temp run against cherry-pick SMW until SMW 3.2.3 is available
    # temp stay with MW 1.34 until all SMW test are passing for 1.35
    - env: DB=mysql; MW=REL1_34; SMW='dev-master#229e166 as 3.2.2'; TYPE=coverage
      php: 7.3

before_install:
  # MW is not yet compatible with Composer 2.x, see https://phabricator.wikimedia.org/T266417
  - composer self-update --1

install:
  - bash ./build/travis/install-mediawiki.sh
  - bash ./build/travis/install-semantic-result-formats.sh

script:
  - bash ./build/travis/run-tests.sh

cache:
  directories:
    - $HOME/.composer/cache
