language: php

env:
  - THENEEDFORTHIS=FAIL

matrix:
  include:
    - env: DB=mysql; MW=1.25.1
      php: 5.6
    - env: DB=sqlite; MW=1.23.0
      php: 5.4
  exclude:
    - env: THENEEDFORTHIS=FAIL

install:
  - bash ./build/travis/install-mediawiki.sh
  - bash ./build/travis/install-semantic-result-formats.sh

script:
  - bash ./build/travis/run-tests.sh

notifications:
  irc:
    channels:
      - "chat.freenode.net#semantic-mediawiki"
    on_success: never
    on_failure: always
